config/routes.rb
Rails.application.routes.draw do
  root 'time_slots#find'

  get 'calendar/:id', to: 'calendar#show', as: 'calendar'
  get 'time_slots', to: 'time_slots#show', as: 'show_time_slots'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :calendar, inverse_of: :appointments
  has_one :time_slot
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  has_many :time_slots, inverse_of: :calendar
  has_many :appointments, inverse_of: :calendar

  validates :name, presence: true

  def last_appointments
    appointments.where(completed: true).order(start: :desc).first(10)
  end

  def next_appointments
    appointments.where(completed: false).order(start: :desc)
  end
end

app/models/time_slot.rb
class TimeSlot < ApplicationRecord
  include Finder

  belongs_to :calendar, inverse_of: :time_slots
  belongs_to :appointment, optional: true
  belongs_to :time_slot_type, inverse_of: :time_slots

  delegate :slot_size, :name, to: :time_slot_type

  validates :start_time, :end_time, presence: true

  def self.available(params)
    Finder::TimeSlotFinder.new(params).find_time_slots
  end
end

app/models/time_slot_type.rb
class TimeSlotType < ApplicationRecord
  has_many :time_slots, inverse_of: :time_slot_type

  validates :name, :slot_size, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def show
    calendar = Calendar.find(params[:id])
    @last_appointments = calendar.last_appointments
    @next_appointments = calendar.next_appointments
  end
end

app/controllers/time_slots_controller.rb
class TimeSlotsController < ApplicationController
  def find
    @calendars = Calendar.all
    @time_slot_types = TimeSlotType.all
  end

  def show
    @time_slots = TimeSlot.available(object_params)
  end

  private
  def object_params
    params.require(:time_slot).permit(:from, :to, :time_slot_type, :duration,
      calendars: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calendar/_table.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Start date</th>
      <th scope="col">End date</th>
    </tr>
  </thead>
  <tbody>
    <% collection.each do |object| %>
      <tr>
          <td><%= object.id %></td>
          <td><%= object.start %></td>
          <td><%= object.end %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/calendar/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h1> Next appointments </h1>
  </div>
  <div class="col-md-12">
    <%= render partial: 'table', locals: { collection: @next_appointments } %>
  </div>
  <hr>
  <div class="col-md-12">
    <h1> Last appointments </h1>
  </div>
  <div class="col-md-12">
    <%= render partial: 'table', locals: { collection: @last_appointments } %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeetingsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <%= link_to 'Appointment', root_path, class: 'navbar-brand' %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
             <%= link_to 'Book appointment', root_path, class: 'nav-link' %></a>
          </li>
<!--          <%# Calendar.all.each do |calendar| %>
            <li class="nav-item">
              <%#= link_to calendar.name, calendar_path(id: calendar.id), class: 'nav-link' %></a>
            </li>
          <%# end %>
-->
        </ul>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/time_slots/_table.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Start date</th>
      <th scope="col">End date</th>
    </tr>
  </thead>
  <tbody>
    <% collection.each do |object| %>
      <tr>
          <td><%= object[:start_time] %></td>
          <td><%= object[:end_time] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/time_slots/find.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1> Book appointment </h1>
    </div>
  </div>
    <%= simple_form_for :time_slot, url: show_time_slots_path, method: :get do |f| %>
      <fieldset>
        <div class="form-group">
          <label>Calendars (ctrl + click to select multiple calendars)</label>
          <%= f.input :calendars, collection: @calendars, input_html: { class: "form-control", multiple: true }, include_blank: false, include_hidden: false, label: false %>
        </div>
        <div class="form-group">
          <label>From</label>
          <%= f.input :from, input_html: { class: "form-control" }, label: false, as: :datetime_picker %>
        </div>
        <div class="form-group">
          <label>To</label>
          <%= f.input :to, input_html: { class: "form-control" }, label: false, as: :datetime_picker %>
        </div>
        <div class="form-group">
          <label>Duration (in minutes)</label>
          <%= f.input :duration, input_html: { class: "form-control" }, label: false, as: :integer %>
        </div>
        <div class="form-group">
          <label>Appointment type</label>
          <%= f.input :time_slot_type, collection: @time_slot_types, input_html: { class: "form-control" }, label: false, required: false %>
        </div>
        <%= f.submit 'Find availability', class: "btn btn-primary" %>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/time_slots/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h1> Available appointments </h1>
  </div>
  <div class="col-md-12">
    <%= render partial: 'table', locals: { collection: @time_slots } %>
  </div>
</div>